application: graph-shortestpath
version: 8
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /javascript
  static_dir: javascript
  
- url: /images
  static_dir: images

- url: /sign
  script: graph.py
  
- url: /.*
  script: graph.py
  

